from typing import overload

class VoidElement:
    @overload
    def __init__(self, **attrs: str): ...
    @overload
    def __init__(self, attrs: dict): ...

class Element:
    @overload
    def __init__(self, **attrs: str): ...
    @overload
    def __init__(self, attrs: dict): ...

def __getattr__(name: str) -> Element: ...
